project/comunidad/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "comunidad"

urlpatterns = [
    path("", TemplateView.as_view(template_name="comunidad/index.html"), name="index"),
    path("miembro_create/", views.MiembroCreate.as_view(), name="miembro_create"),
    path("miembro_list/", views.MiembroList.as_view(), name="miembro_list"),
    path("miembro_detail/<int:pk>", views.MiembroDetail.as_view(), name="miembro_detail"),
    path("miembro_delete/<int:pk>", views.MiembroDelete.as_view(), name="miembro_delete"),
    path("miembro_update/<int:pk>", views.MiembroUpdate.as_view(), name="miembro_update"),
    path("casascomunidad/list/", views.CasasComunidadList.as_view(), name="casascomunidad_list"),
    path("casascomunidad/detail/<int:pk>", views.CasasComunidadDetail.as_view(), name="casascomunidad_detail"),
    path("casascomunidad/create/", views.CasasComunidadCreate.as_view(), name="casascomunidad_create"),
    path("casascomunidad/update/<int:pk>/", views.CasasComunidadUpdate.as_view(), name="casascomunidad_update"),
    path("casascomunidad/delete/<int:pk>/", views.CasasComunidadDelete.as_view(), name="casascomunidad_delete"),


    
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path("", include("home.urls")),
    path("comunidad/", include("comunidad.urls")),
    path("publicaciones/", include("publicaciones.urls")),
    path("users/", include("users.urls")),
         
]

project/home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("abaut/", views.abaut, name="abaut")
]

urlpatterns += staticfiles_urlpatterns()

project/publicaciones/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "publicaciones"

urlpatterns = [
    path("", TemplateView.as_view(template_name="publicaciones/index.html"), name="index"),
    path("publicaciones_list/", views.PublicacionesList.as_view(), name="publicaciones_list"),
    path("publicaciones_detail/<int:pk>/", views.PublicacionesDetail.as_view(), name="publicaciones_detail"),
    path("publicaciones_create/", views.PublicacionesCreate.as_view(), name="publicaciones_create"),
    path("publicaciones_delete/<int:pk>/", views.PublicacionesDelete.as_view(), name="publicaciones_delete"),
    path("publicaciones_update/<int:pk>/", views.PublicacionesUpdate.as_view(), name="publicaciones_update"),    
]

project/publicaciones/models.py
from django.db import models

# Create your models here.
class Publicaciones(models.Model):
    titulo = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=300)
    cantidad = models.IntegerField(null=True, blank=True)
    precio = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)
    email_contacto = models.EmailField(null=True,blank=True)
    telefono_contacto = models.IntegerField(null=True,blank=True)
    
    class Meta:
        verbose_name = "Publicación"
        verbose_name_plural = "Publicaciones"
        
    def __str__(self):
        return self.titulo

project/publicaciones/forms.py
from django import forms

from . import models

class PublicacionesForm(forms.ModelForm):
    class Meta:
        model = models.Publicaciones
        fields = ["titulo","descripcion","cantidad","precio","email_contacto","telefono_contacto"]

project/publicaciones/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from . import models, forms
class PublicacionesList(ListView):
    model = models.Publicaciones
    
    def get_queryset(self):
        consulta = self.request.GET.get("buscar")
    
        if consulta:       
            object_list = models.Publicaciones.objects.filter(titulo__icontains=consulta)
        else:        
            object_list = models.Publicaciones.objects.all()    
        return object_list
    
class PublicacionesDetail(DetailView):
    model = models.Publicaciones
    
    
class PublicacionesCreate(CreateView):
    model = models.Publicaciones
    form_class = forms.PublicacionesForm
    success_url = reverse_lazy("publicaciones:publicaciones_list")
    
class PublicacionesUpdate(UpdateView):
    model = models.Publicaciones
    form_class = forms.PublicacionesForm
    success_url = reverse_lazy("publicaciones:publicaciones_list")
    
class PublicacionesDelete(DeleteView):
    model = models.Publicaciones
    success_url = reverse_lazy("publicaciones:publicaciones_list")

project/publicaciones/templates/publicaciones/crear_publicacion.html
{% extends 'home/base.html' %}
{% block content %}    

<body>
    <div class="col-md-3 mb-3">
        <div class="m-3  text-md-start ">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p}}
                
                <button class="btn btn-success " type="submit">Guardar</button>
                 
            </form>
            <a class="btn btn-outline-dark ms-0   " href="{% url 'publicaciones:index' %}">Volver</a>
        </div>
    </div>
</body>


{% endblock content %}
</html>

project/publicaciones/templates/publicaciones/index.html
{% extends 'home/base.html' %}

<body>
    {% block content %}
    </html>
    <body>
        <h2 class="m-3 ">Publicaciones</h2> 
        {% if user.is_authenticated %}
        <a class="btn btn-success m-3" href="{% url 'publicaciones:publicaciones_create' %}">Crear nueva publicacion</a>
        {% endif %}
        <a class="btn btn-success m-3" href="{% url 'publicaciones:publicaciones_list' %}">Lista de publicaciones</a>
        <a class="btn btn-outline-dark m-3 m-3" href="{% url 'home:index' %}">Home</a>
    </body>
    </html>
    {% endblock content %}
    

project/publicaciones/templates/publicaciones/publicaciones_confirm_delete.html
{% extends 'home/base.html' %}


{% block content %}

<h3 class="text-center ">Eliminar publicacion</h3>
    <p class="fs-5 fst-italic text-center  ">Esta por eliminar {{ object.titulo }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="text-center">
            <button type="submit" class="btn btn-danger btn-sm mx-auto">Confirmar</button>
        </div>
    </form>
    
        <a href="{% url 'comunidad:miembro_list' %}" class="btn btn-dark mx-auto">Volver</a>
    
{% endblock content %}

project/publicaciones/templates/publicaciones/publicaciones_detail.html
{% extends 'home/base.html' %}

{% block content %}

    <ul>
        <h2>{{object.titulo}}</h2>        
        <p>{{object.descripcion}}</p>        
        <p>Precio: ${{object.precio}}</p>
        <p>Datos de contaco:</p>
        <li>
            email: {{object.email_contacto}} 
        </li>   
        <li> 
            Telefono: {{object.telefono_contacto}}
        </li> 
    </ul>
    <a class="btn btn-outline-dark m-3 m-3" href="{% url 'publicaciones:publicaciones_list' %}">Volver</a>
{% endblock content %}

project/publicaciones/templates/publicaciones/publicaciones_form.html
{% extends 'home/base.html' %}
{% block content %}    

<body>
    <div class="col-md-3 mb-3">
        <div class="m-3  text-md-start ">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p}}
                
                <button class="btn btn-success " type="submit">Guardar</button>
                <a class="btn btn-outline-dark ms-0   " href="{% url 'publicaciones:index' %}">Volver</a> 
            </form>
            
        </div>
    </div>
</body>


{% endblock content %}
</html>

project/publicaciones/templates/publicaciones/publicaciones_list.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

<div class="row gx-4 gx-lg-5 align-items-center my-5">
<div class="container px-4 px-lg-5">  
<div class="row gx-4 gx-lg-5">
    <h2 class="m-3 ">Lista de publicaciones</h2>
    
    <div class="py-4 m-3">
        <form action="" method="get">
            <input type="text" name="buscar" placeholder="Buscar publicacion">
            <button type="submit">Buscar</button>
            {% if not object_list %}
                <p>No se encontraron publicaciones que coincidan con la búsqueda.</p>
            {% endif %}
        </form>
    </div>        
        
        {% for publicacion in object_list %}
        <div class="col-md-3 mb-4">
            <div class="card h-100">
                <div class="card-body ">
                    <h2 class="card-title text-center">{{ publicacion.titulo }}</h2>
                </div>
                <div class="d-flex justify-content-center align-items-center">
                    <img class="img-fluid rounded" src="{% static 'home/images/no-image.jpeg' %}" alt="..." style="max-height: 90%; width: auto;" />
                </div>
                <div class="card-footer text-center">
                    <a class="btn btn-primary btn-sm" href="{% url 'publicaciones:publicaciones_detail' publicacion.id %}">Ver publicación</a>
                    {% if user.is_authenticated %} 
                    <a class="btn btn-primary btn-sm" href="{% url 'publicaciones:publicaciones_update' publicacion.id %}">Actualizar</a>
                    <a class="btn btn-primary btn-sm" href="{% url 'publicaciones:publicaciones_delete' publicacion.id %}">Eliminar</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}  
    
      
</div>
</div>
</div>  
    <a class="btn btn-outline-dark m-3 m-3" href="{% url 'publicaciones:index' %}">Volver</a>
</body>
    
{% endblock content %}