project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path("", include("home.urls")),
    path("comunidad/", include("comunidad.urls")),
    path("publicaciones/", include("publicaciones.urls")),
    path("users/", include("users.urls")),
         
]

project/home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("abaut/", views.abaut, name="abaut")
]

urlpatterns += staticfiles_urlpatterns()

project/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("", TemplateView.as_view(template_name="users/index.html"), name="index"),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('registro/', views.RegistroView.as_view(template_name="users/registro.html"), name='registro'),
    path('inicio-sesion/', views.InicioSesionView.as_view(template_name="users/inicio-sesion.html"), name='inicio-sesion'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('cerrar-sesion/', views.cerrar_sesion, name='logout')
]

project/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    numero_telefono = models.CharField(max_length=15)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        return self.username

project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from .models import CustomUser


class RegistroForm(UserCreationForm):
    nombre = forms.CharField(max_length=30)
    apellido = forms.CharField(max_length=30)
    email = forms.EmailField()
    numero_telefono = forms.CharField(max_length=15)
    fecha_nacimiento = forms.DateField()

    class Meta:
        model = CustomUser
        fields = ('nombre', 'apellido', 'username', 'email', 'numero_telefono', 'fecha_nacimiento', 'password1', 'password2')

class InicioSesionForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password')

class EditarPerfilForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('nombre', 'apellido', 'email', 'numero_telefono', 'fecha_nacimiento')

project/users/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .forms import RegistroForm, InicioSesionForm, EditarPerfilForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


class RegistroView(CreateView):
    form_class = RegistroForm
    success_url = reverse_lazy('home:index')
    template_name = 'registro.html'

class InicioSesionView(LoginView):
    form_class = InicioSesionForm        
    template_name = 'inicio-sesion.html'
    
@login_required
def perfil(request):
    user = request.user 
    return render(request, 'users/perfil.html', {'user': user})

@login_required
def editar_perfil(request):
    if request.method == 'POST':
        form = EditarPerfilForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:perfil')
    else:
        form = EditarPerfilForm(instance=request.user)
    return render(request, 'users/editar_perfil.html', {'form': form})

def cerrar_sesion(request):
    logout(request)
    return redirect('home:index')

project/users/templates/users/editar_perfil.html
{% extends 'home/base.html' %}

{% block content %}
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="container px-4 px-lg-5">  
        <div class="row gx-4 gx-lg-5">
            <h2>Editar Perfil</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Guardar cambios</button>
            </form>
        </div>
    </div>
</div>               
{% endblock content %}

project/users/templates/users/index.html
{% extends 'home/base.html' %}
{% block content %}
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="container px-4 px-lg-5">         
        <strong><p class="m-lg-3  mx-auto">Regístrate y se parte de nuestra comunidad, podrás crear publicaciones con tus creaciones y dar a conocer tus habilidades</p></strong>
        <a class="btn btn-success m-3 text-center " href="{% url 'users:registro' %}">Crear nuevo usuario</a>
        <a class="btn btn-success m-3text-center " href="{% url 'users:inicio-sesion' %}">Iniciar sesión</a>
        <a class="btn btn-outline-dark m-3 m-3 text-center " href="{% url 'home:index' %}">Home</a>        
    </div>
</div>
{% endblock content %}

project/users/templates/users/inicio-sesion.html
{% extends 'home/base.html' %}

{% block content %}
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="container px-4 px-lg-5">  
        <div class="row gx-4 gx-lg-5"> 
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Iniciar Sesión</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

project/users/templates/users/login.html
{% extends 'home/base.html' %}

{% block content %} 
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="container px-4 px-lg-5">                
        <h1><strong>Has iniciado sesión</strong></h1>
        <a class="btn btn-outline-dark m-3 m-3" href="{% url 'home:index' %}">Home</a>
        <a class="btn btn-outline-dark m-3 m-3" href="{% url 'users:perfil' %}">Mi perfil</a>        
    </div>
</div>
{% endblock content %}
    

project/users/templates/users/perfil.html
{% extends 'home/base.html' %}
{% block content %}
<div class="row gx-4 gx-lg-5 align-items-center my-5">
  <div class="container px-4 px-lg-5">  
      <div class="row gx-4 gx-lg-5">        
          <h1>Mi Perfil</h1>
            <div class="profile-info">
              <div class="profile-picture"></div>   
                <div class="profile-details">
                <p><strong>Nombre:</strong> {{ user.nombre }} {{ user.apellido }}</p>
                <p><strong>Email:</strong> {{ user.email }}</p>
                <p><strong>Fecha de Nacimiento:</strong> {{ user.fecha_nacimiento }}</p>
                <p><strong>Número de Teléfono:</strong> {{ user.numero_telefono }}</p>
              </div>
            </div>
          </div>
          <a class="btn btn-dark   m-3 m-3" href="{% url 'users:editar_perfil' %}">Editar perfil</a>
          <a class="btn btn-outline-dark m-3 m-3" href="{% url 'home:index' %}">Home</a>
        </div>
      </div>      
    </div>  
  
  
{% endblock content %}  
    

project/users/templates/users/registro.html
{% extends 'home/base.html' %}

{% block content %}
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="container px-4 px-lg-5">  
        <div class="row gx-4 gx-lg-5">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Registrarse</button>
            </form>
        </div>
    </div>
</div>            
        
{% endblock content %}