project/comunidad/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "comunidad"

urlpatterns = [
    path("", TemplateView.as_view(template_name="comunidad/index.html"), name="index"),
    path("miembro_create/", views.MiembroCreate.as_view(), name="miembro_create"),
    path("miembro_list/", views.MiembroList.as_view(), name="miembro_list"),
    path("miembro_detail/<int:pk>", views.MiembroDetail.as_view(), name="miembro_detail"),
    path("miembro_delete/<int:pk>", views.MiembroDelete.as_view(), name="miembro_delete"),
    path("miembro_update/<int:pk>", views.MiembroUpdate.as_view(), name="miembro_update"),
    path("casascomunidad/list/", views.CasasComunidadList.as_view(), name="casascomunidad_list"),
    path("casascomunidad/detail/<int:pk>", views.CasasComunidadDetail.as_view(), name="casascomunidad_detail"),
    path("casascomunidad/create/", views.CasasComunidadCreate.as_view(), name="casascomunidad_create"),
    path("casascomunidad/update/<int:pk>/", views.CasasComunidadUpdate.as_view(), name="casascomunidad_update"),
    path("casascomunidad/delete/<int:pk>/", views.CasasComunidadDelete.as_view(), name="casascomunidad_delete"),


    
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path("", include("home.urls")),
    path("comunidad/", include("comunidad.urls")),
    path("publicaciones/", include("publicaciones.urls")),
    path("users/", include("users.urls")),
         
]

project/home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("abaut/", views.abaut, name="abaut")
]

urlpatterns += staticfiles_urlpatterns()

project/comunidad/models.py
from django.db import models

# Create your models here.
class CasasComunidad(models.Model):
    nombre_casa = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500)
    
    def __str__(self):
        return self.nombre_casa
    
    class Meta:
        verbose_name = "Casa"
        verbose_name_plural = "Casas"
        
class Miembro(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)
    profesion = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    casa_comarca = models.ForeignKey(CasasComunidad, on_delete=models.SET_NULL,null=True,blank=True, verbose_name="Hogar en la comarca")
    
    class Meta:
        verbose_name = "Miembro"
        verbose_name_plural = "Miembros"
    
    def __str__(self):
        return f"{self.nombre.title()} {self.apellido.title()}"
    

project/comunidad/forms.py
from django import forms

from . import models

class MiembroForm(forms.ModelForm):
    class Meta:
        model = models.Miembro
        fields = ["nombre","apellido","nacimiento","profesion","email","casa_comarca"]
        
class CasasComunidadForm(forms.ModelForm):
    class Meta:
        model = models.CasasComunidad
        fields = ["nombre_casa","descripcion"]

project/comunidad/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from . import models, forms
class CasasComunidadList(ListView):
    model = models.CasasComunidad
    
class CasasComunidadDetail(DetailView):
    model = models.CasasComunidad
    template_name = "comunidad/casascomunidad_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        casa = context['object']
        miembros = casa.miembro_set.all()
        context['miembros'] = miembros
        return context
    
class CasasComunidadCreate(CreateView):
    model = models.CasasComunidad
    form_class = forms.CasasComunidadForm
    success_url = reverse_lazy("comunidad:casascomunidad_list")
    
class CasasComunidadUpdate(UpdateView):
    model = models.CasasComunidad
    form_class = forms.CasasComunidadForm
    success_url = reverse_lazy("comunidad:casascomunidad_list")
    
class CasasComunidadDelete(DeleteView):
    model = models.CasasComunidad
    success_url = reverse_lazy("comunidad:casascomunidad_list")
    
    
class MiembroList(ListView):
    model = models.Miembro
    
    def get_queryset(self):
        consulta = self.request.GET.get("buscar")
    
        if consulta:       
            object_list = models.Miembro.objects.filter(nombre__icontains=consulta)
        else:        
            object_list = models.Miembro.objects.all()    
        return object_list
    
class MiembroDetail(DetailView):
    model = models.Miembro
    
class MiembroCreate(CreateView):
    model = models.Miembro
    form_class = forms.MiembroForm
    success_url = reverse_lazy("comunidad:miembro_list")
    
class MiembroUpdate(UpdateView):
    model = models.Miembro
    form_class = forms.MiembroForm
    success_url = reverse_lazy("comunidad:miembro_list")
    
class MiembroDelete(DeleteView):
    model = models.Miembro
    success_url = reverse_lazy("comunidad:miembro_list")
    

    

project/comunidad/templates/comunidad/casascomunidad_confirm_delete.html
{% extends 'home/base.html' %}


{% block content %}

<h3 class="text-center ">Eliminar casa de la comarca</h3>
    <p class="fs-5 fst-italic text-center  ">Esta por eliminar {{ object.nombre_casa }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="text-center">
            <button type="submit" class="btn btn-danger btn-sm mx-auto">Confirmar</button>
        </div>
    </form>
    
        <a href="{% url 'comunidad:casascomunidad_list' %}" class="btn btn-dark mx-auto">Volver</a>
    
{% endblock content %}

project/comunidad/templates/comunidad/casascomunidad_detail.html
{% extends 'home/base.html' %}

{% block content %}

    <ul>
        <h2>{{object.nombre_casa}}</h2>
        <p>{{object.descripcion}}</p>
        
        <h2>Miembros de esta Casa:</h2>
    <ul>
        {% for miembro in miembros %}
            <li>{{ miembro.nombre }} {{ miembro.apellido }} - (contacto : {{miembro.email}})</li>
        {% endfor %}
    </ul>
    </ul>
    <a class="btn btn-outline-dark m-3 m-3" href="{% url 'comunidad:casascomunidad_list' %}">Volver</a>
{% endblock content %}

project/comunidad/templates/comunidad/casascomunidad_form.html
{% extends 'home/base.html' %}

{% block content %}    

<body>
    <div class="col-md-3 mb-3">
        <div class="m-3  text-md-start ">
            
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p}}                
                <button class="btn btn-success " type="submit">Guardar</button>                
            </form>
            <a class="btn btn-outline-dark ms-0   " href="{% url 'comunidad:index' %}">Volver</a>
        </div>
    </div>
</body>

{% endblock content %}
</html>

project/comunidad/templates/comunidad/casascomunidad_list.html
{% extends 'home/base.html' %}

{% load static %}
{% block content %}
<div class="row gx-4 gx-lg-5 align-items-center my-5">
<div class="container px-4 px-lg-5">  
<div class="row gx-4 gx-lg-5">             
        
        {% for casa in object_list %}
        <div class="col-md-4 mb-5">
            <div class="card h-100">        
                <div class="card-body">
                    <h2 class="card-title text-center ">{{ casa.nombre_casa }}</h2>                                               
                    
                </div>
                <div class="col-12 mb-1 text-center">
                    <img class="img-fluid rounded" src="{% static 'home/images/casa_comarca.png' %}" alt="..." style="max-height: 100%; width: auto;" />
                </div>
        
                <div class="card-footer text-center "><a class="btn btn-primary btn-sm" href="{% url 'comunidad:casascomunidad_detail' casa.id %}">Entrar a la casa</a>
                    {% if user.is_authenticated %}
                        <a class="btn btn-primary btn-sm" href="{% url 'comunidad:casascomunidad_update' casa.id %}">Actualizar</a>
                        <a class="btn btn-primary btn-sm" href="{% url 'comunidad:casascomunidad_delete' casa.id %}">Eliminar</a>
                    {% endif %}
                    
                </div>
            </div>
        </div>
        {% endfor %}  
    </div>
    {% if user.is_authenticated %} 
    <a class="btn btn-success m-3" href="{% url 'comunidad:casascomunidad_create' %}">Crear nueva casa</a> 
    {% endif %}
    <a class="btn btn-outline-dark m-3 m-3" href="{% url 'comunidad:index' %}">Volver</a>
    {% if not user.is_authenticated %} 
    <p>Para crear nuevas casas tienes que estar registrado</p>
    {% endif %}
</body>
    
{% endblock content %}

project/comunidad/templates/comunidad/crear_casa.html
{% extends 'home/base.html' %}

{% block content %}    

<body>
    <div class="col-md-3 mb-3">
        <div class="m-3  text-md-start ">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p}}
                
                <button class="btn btn-success " type="submit">Guardar</button>
                <a class="btn btn-outline-dark ms-0   " href="{% url 'comunidad:index' %}">Volver</a>
            </form>
            
        </div>
    </div>
</body>

{% endblock content %}
</html>

project/comunidad/templates/comunidad/crear_miembro.html
{% extends 'home/base.html' %}
{% block content %}   

<body>
    <div class="col-md-3 mb-3">
        <div class="m-3  text-md-start ">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p}}
                
                <button class="btn btn-success " type="submit">Guardar</button>
                <a class="btn btn-outline-dark ms-0   " href="{% url 'comunidad:lista_completa' %}">Volver</a>
            </form>
            
        </div>
    </div>
</body>

{% endblock content %}

project/comunidad/templates/comunidad/index.html
{% extends 'home/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    </html>
    <body>
        <h2 class="m-3 ">Comunidad</h2>        
        <a class="btn btn-success m-3 " href="{% url 'comunidad:casascomunidad_list' %}">Casas de artesanos</a>
        <a class="btn btn-success m-3" href="{% url 'comunidad:miembro_list' %}">Lista de miembros</a>        
        <a class="btn btn-outline-dark m-3" href="{% url 'home:index' %}">Home</a>
    </body>
    </html>
    {% endblock content %}
    

project/comunidad/templates/comunidad/miembro_confirm_delete.html
{% extends 'home/base.html' %}


{% block content %}

<h3 class="text-center ">Eliminar miembro de la Comarca</h3>
    <p class="fs-5 fst-italic text-center  ">Esta por eliminar {{ object.nombre }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="text-center">
            <button type="submit" class="btn btn-danger btn-sm mx-auto">Confirmar</button>
        </div>
    </form>
    
        <a href="{% url 'comunidad:miembro_list' %}" class="btn btn-dark mx-auto">Volver</a>
    
{% endblock content %}

project/comunidad/templates/comunidad/miembro_detail.html
{% extends 'home/base.html' %}

{% block content %}

    <ul>
        <h2>Nombre: {{object.nombre}} {{object.apellido}}</h2>
        <p>{{object.casa_comarca}}</p>
        <p>{{object.email}}</p>    
    </ul>
    <a class="btn btn-outline-dark m-3 m-3" href="{% url 'comunidad:miembro_list' %}">Volver</a>
{% endblock content %}

project/comunidad/templates/comunidad/miembro_form.html
{% extends 'home/base.html' %}
{% block content %}   

<body>
    <div class="col-md-3 mb-3">
        <div class="m-3  text-md-start ">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p}}
                
                <button class="btn btn-success " type="submit">Guardar</button>
                <a class="btn btn-outline-dark ms-0   " href="{% url 'comunidad:miembro_list' %}">Volver</a>
            </form>
            
        </div>
    </div>
</body>

{% endblock content %}

project/comunidad/templates/comunidad/miembro_list.html
{% extends 'home/base.html' %}


{% block content %}     
    
<body>
    <h2 class="m-3 ">Lista de todos los miembros de la comarca</h2>
    <div class="py-4 m-3">
        <form action="" method="get">
            <input type="text" name="buscar" placeholder="Buscar artesano">
            <button type="submit">Buscar</button>
            {% if not object_list %}
                <p>No se encontraron usuarios que coincidan con la búsqueda.</p>
            {% endif %}
        </form>
    </div> 
    
    <ul>
        {% for miembro in object_list %}
            <li>{{miembro.nombre}} {{miembro.apellido}} -- {{miembro.casa_comarca}}</li>
            
            <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'comunidad:miembro_detail' miembro.id %}">Contactar</a>
                {% if user.is_authenticated %} 
                <a class="btn btn-primary btn-sm" href="{% url 'comunidad:miembro_update' miembro.id %}">Actualizar</a>
                <a class="btn btn-primary btn-sm" href="{% url 'comunidad:miembro_delete' miembro.id %}">Eliminar</a>
                {% endif %}
            </div>      
        {% endfor %}
    </ul>
    <a class="btn btn-success m-3" href="{% url 'comunidad:miembro_create' %}">Crear nuevo miembro</a>
    <a class="btn btn-outline-dark m-3 m-3" href="{% url 'comunidad:index' %}">Volver</a>
    {% if not user.is_authenticated %} 
    <p class="m-lg-3">Puedes ser miembro de la comunidad sin estar registrado y darte a conocer!!</p>
    {% endif %}
</body>


 
{% endblock content %}