project/comunidad/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "comunidad"

urlpatterns = [
    path("", TemplateView.as_view(template_name="comunidad/index.html"), name="index"),
    path("miembro_create/", views.MiembroCreate.as_view(), name="miembro_create"),
    path("miembro_list/", views.MiembroList.as_view(), name="miembro_list"),
    path("miembro_detail/<int:pk>", views.MiembroDetail.as_view(), name="miembro_detail"),
    path("miembro_delete/<int:pk>", views.MiembroDelete.as_view(), name="miembro_delete"),
    path("miembro_update/<int:pk>", views.MiembroUpdate.as_view(), name="miembro_update"),
    path("casascomunidad/list/", views.CasasComunidadList.as_view(), name="casascomunidad_list"),
    path("casascomunidad/detail/<int:pk>", views.CasasComunidadDetail.as_view(), name="casascomunidad_detail"),
    path("casascomunidad/create/", views.CasasComunidadCreate.as_view(), name="casascomunidad_create"),
    path("casascomunidad/update/<int:pk>/", views.CasasComunidadUpdate.as_view(), name="casascomunidad_update"),
    path("casascomunidad/delete/<int:pk>/", views.CasasComunidadDelete.as_view(), name="casascomunidad_delete"),


    
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path("", include("home.urls")),
    path("comunidad/", include("comunidad.urls")),
    path("publicaciones/", include("publicaciones.urls")),
    path("users/", include("users.urls")),
         
]

project/home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("abaut/", views.abaut, name="abaut")
]

urlpatterns += staticfiles_urlpatterns()

project/publicaciones/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "publicaciones"

urlpatterns = [
    path("", TemplateView.as_view(template_name="publicaciones/index.html"), name="index"),
    path("publicaciones_list/", views.PublicacionesList.as_view(), name="publicaciones_list"),
    path("publicaciones_detail/<int:pk>/", views.PublicacionesDetail.as_view(), name="publicaciones_detail"),
    path("publicaciones_create/", views.PublicacionesCreate.as_view(), name="publicaciones_create"),
    path("publicaciones_delete/<int:pk>/", views.PublicacionesDelete.as_view(), name="publicaciones_delete"),
    path("publicaciones_update/<int:pk>/", views.PublicacionesUpdate.as_view(), name="publicaciones_update"),    
]

project/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("", TemplateView.as_view(template_name="users/index.html"), name="index"),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('registro/', views.RegistroView.as_view(template_name="users/registro.html"), name='registro'),
    path('inicio-sesion/', views.InicioSesionView.as_view(template_name="users/inicio-sesion.html"), name='inicio-sesion'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('cerrar-sesion/', views.cerrar_sesion, name='logout')
]

project/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from publicaciones.models import Publicaciones
# Create your views here.

def index(request):
    publicacion = Publicaciones.objects.all()  # Consulta todas las publicaciones en la base de datos
    return render(request, 'home/index.html', {'publicaciones': publicacion})
    

def abaut(request):
    return render(request, "home/abaut.html")

project/home/templates/home/abaut.html
{% extends 'home/base.html' %}
{% block content %}
<body>
    <header>
        <h1 class="m-5 ">Sobre Nosotros - La Comarca</h1>
    </header>
    <div class="container">
        <h2>¿Quiénes somos?</h2>
        <p>Somos un grupo diverso de entusiastas de la Comarca, desde los amantes de la tecnología hasta los aficionados a la jardinería. Nos enorgullece ser la plataforma de elección para la comunidad local.</p>

        <h2>¿Qué hacemos?</h2>
        <p>En La Comarca, brindamos una plataforma segura y conveniente para que los miembros publiquen sus clasificados de venta.
            <h2>¿Por qué elegir La Comarca?</h2>
        <ul class="feature-list">
            <li>
                <div class="icon">✔️</div>
                <p>Local y Confiable: Conocemos la Comarca y confiamos en que encontrarás justo lo que necesitas dentro de nuestra comunidad.</p>
            </li>
            <li>
                <div class="icon">🔐</div>
                <p>Seguridad: Protegemos tus datos y fomentamos la transparencia en todas las transacciones.</p>
            </li>
            <li>
                <div class="icon">🚀</div>
                <p>Facilidad de Uso: Nuestra plataforma es intuitiva y sencilla de navegar. Puedes buscar y publicar anuncios en cuestión de minutos.</p>
            </li>
            <li>
                <div class="icon">👥</div>
                <p>Comunidad Activa: Únete a una comunidad activa de compradores y vendedores, con opciones para discutir, hacer preguntas y socializar con otros miembros.</p>
            </li>
        </ul>
    </div>
    <footer>
        <strong><p class="text-center ">¡Gracias por ser parte de nuestra comunidad!</p></strong>
    </footer>
</body>
{% endblock content %}

project/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>La comarca</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'home/navbar.html' %}
        
        <!-- Page Content-->
        {% block content %}                 
        {% endblock content %}
        
        {% include 'home/footer.html' %}
            
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

project/home/templates/home/card.html
{% load static %}
<div class="col-md-4 mb-5">
    <div class="card h-100">        
        <div class="card-body">
            <h2 class="card-title">{{ card }}</h2>                                               
            <p class="card-text">.</p>
        </div>
        <div class="col-12  mb-1 "><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'home/images/comarca.jpeg' %}" alt="..." />
        </div>

        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Ver publicación</a></div>
    </div>
</div>

project/home/templates/home/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; La comarca 2023</p></div>
</footer>

project/home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<div class="container px-4 px-lg-5">
                      
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'home/images/comarca.jpeg' %}" alt="..." /></div>
        <div class="col-lg-5">
            <h1 class="font-weight-light text-center ">La comarca</h1>
            <strong><p class="text-center text-body  ">
                "Tu comunidad local para comprar, vender y conectarte."</p></strong>
            <div class="text-center ">            
            <a class="btn btn-primary" href="{% url 'users:index' %}">Se parte!</a>
            <a class="btn btn-primary" href="{% url 'home:abaut' %}">Nosotros!</a>
            </div>
        </div>
    </div>
    
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">             
        
            {% for publicacion in publicaciones %}
            <div class="col-md-3 mb-4">
                <div class="card h-100">
                    <div class="card-body ">
                        <h2 class="card-title text-center">{{ publicacion.titulo }}</h2>
                    </div>
                    <div class="d-flex justify-content-center align-items-center">
                        <img class="img-fluid rounded" src="{% static 'home/images/no-image.jpeg' %}" alt="..." style="max-height: 90%; width: auto;" />
                    </div>
            
                    <div class="card-footer text-center" ><a class="btn btn-primary btn-sm" href="{% url 'publicaciones:publicaciones_detail' publicacion.id %}" >Ver publicación</a></div>
                </div>
            </div>   
            {% endfor %}
        


    </div>
    </div>
{% endblock content %}
</html>

project/home/templates/home/navbar.html
<!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'home:index' %}">LA COMARCA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'comunidad:index' %}">Comunidad</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'publicaciones:index' %}">Publicaciones</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'home:abaut' %}">Sobre nosotros</a></li>
                {% if not user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users:index' %}">Login</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Cerrar Sesión</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>